test:
  image: sagemath/sagemath-dev:develop
  script:
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - for pkg in "flipper curver surface_dynamics"; do sage -pip install ${pkg}; done
    - sage -pip install .
    - DIR="$(pwd)"
    - cd
    - sage -t --force-lib --long ${DIR}/veerer
    - cd ${DIR}/test
    - sage -python run_tests.py
