test: &test
  image: sagemath/sagemath-develop
  script:
    - sage -c "print(\"hello\")"
    - sage -pip install .
    - DIR="$(pwd)"
    - cd
    - sage -t --force-lib --long ${DIR}/veerer

test:8.7:
  << : *test
  image: sagemath/sagemath-dev:8.7

