sage:
  image: sagemath/sagemath-dev:develop
  script:
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - for pkg in "flipper curver surface_dynamics"; do sage -pip install ${pkg}; done
    - sage -pip install .
    - DIR="$(pwd)"
    - cd
    - sage -t --force-lib --long ${DIR}/veerer
    - sage -t --force-lib --long ${DIR}/docs/source
    - sage -python ${DIR}/test/run_tests.py

python:
  script:
    - pip install --user .
    - python test/run_tests.py

python-flipper-curver:
  script:
    - pip install --user flipper
    - pip install --user curver
    - pip install --user .
    - python test/run_tests.py

