# alpine based tests (~ 30sec)
python2:
  image: python:2-alpine
  before_script:
    - export PYTHON="python2" PIP="pip2"
    - ${PIP} install .
    - ${PIP} install pytest
  script:
    - ${PYTHON} test/run_tests.py

python3:
  image: python:3-alpine
  before_script:
    - export PYTHON="python3" PIP="pip3"
    - ${PIP} install .
    - ${PIP} install pytest
  script:
    - ${PYTHON} test/run_tests.py

# debian based tests (between 3 and 5 min)
python3-optional:
  image: debian:bullseye
  before_script:
    - export PYTHON="python3" PIP="pip3"
    - apt-get update
    - apt-get install -y python3 python3-pip python3-pytest python3-numpy python3-pandas python3-cysignals-pari python3-ppl cython3 libgmp-dev libmpfr-dev libmpc-dev libppl-dev
    - ${PIP} install .
    - ${PIP} install networkx flipper curver
  script:
    - ${PYTHON} test/run_tests.py

# sagemath based tests (around 10min)
sage:
  image: sagemath/sagemath-dev:develop
  before_script:
    - export PYTHON="sage -python" PIP="sage -pip"
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - ${PIP} install .
    - ${PIP} install pytest
  script:
    - ${PYTHON} test/run_tests.py
    # NOTE: the sage doctester refuses to execute from the repository because
    # of "wrong" permissions. For that reason we cd to the home directory before
    # running them.
    - DIR="$(pwd)"
    - cd
    - sage -t --force-lib --long ${DIR}/veerer
    - sage -t --force-lib --long ${DIR}/docs/source

sage-optional:
  image: sagemath/sagemath-dev:develop
  before_script:
    - export PYTHON="sage -python" PIP="sage -pip"
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - for pkg in "flipper curver surface_dynamics"; do sage -pip install ${pkg}; done
    - ${PIP} install .
    - ${PIP} install pytest
  script:
    - ${PYTHON} test/run_tests.py
    # NOTE: the sage doctester refuses to execute from the repository because
    # of "wrong" permissions. For that reason we cd to the home directory before
    # running them.
    - DIR="$(pwd)"
    - cd
    - sage -t --force-lib --long --optional=sage,curver,flipper,surface_dynamics ${DIR}/veerer
    - sage -t --force-lib --long --optional=sage,curver,flipper,surface_dynamics ${DIR}/docs/source
